[build]
builder = "dockerfile"

[variables]
SECRET_KEY = "jemDegJUKyoIqdWowuHSmIBBwxIipSqT-secret-key-2024"
DATABASE_URL = "${{DATABASE_PRIVATE_URL}}"
PGHOST = "postgres-6thv.railway.internal"
PGPORT = "5432"
PGDATABASE = "railway"
PGUSER = "postgres"
PGPASSWORD = "${{POSTGRES_PASSWORD}}"
DATABASE_DRIVER = "org.postgresql.Driver"
DATABASE_MAX_POOL_SIZE = "10"
